DonationWeb/config/routes.rb
Rails.application.routes.draw do
  get 'donations/index'


  root 'donations#index'

  resources :donations








end

DonationWeb/app/models/Donation.rb
require 'rubygems'
require 'active_resource' 

class Donation < ActiveResource::Base
  self.site = SVC_BASE_URL
  # self.element_name = "donation"
  self.format = :json
end

DonationWeb/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

DonationWeb/app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  def index
	@donorid
	if params[:donor].blank?
  		@donorid = 100
	else
		@donorid = params[:donor]
	end

	@donations = Donation.find(:all, :from => "#{SVC_BASE_URL}/#{@donorid}/donations.json")
  end

  def new

  end

  def create
	# @fullurl = "#{SVC_BASE_URL}/donors/#{params[:donations][:donorid]}"
	# logger.info @fullurl
	# Donation.site = @fullurl
	# convert to integers
	params[:donations][:donorid] = params[:donations][:donorid].to_i
	params[:donations][:donationamount] = params[:donations][:donationamount].to_i
	d = Donation.new(params[:donations])
	d.save

	redirect_to :action => "index", :donor => params[:donations][:donorid]
  end

end

DonationWeb/app/helpers/application_helper.rb
module ApplicationHelper
end

DonationWeb/app/helpers/donation_helper.rb
module DonationHelper
end

DonationWeb/app/views/donations/index.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">
        Donation Nation
      </a>
    </div>	
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home <span class="sr-only">(current)</span></a></li>
        <li><a href="/donations/new">Make Donation</a></li>
      </ul>
  </div>
</nav>
<div class="row">
	<div class="col-md-2">&nbsp;</div>
	<div class="col-md-8">
		<blockquote>
  		<p>Let's change the world. By giving other people our money.</p>
  		<footer>Richard Seroter</footer>
		</blockquote>
	</div>
	<div class="col-md-2">&nbsp;</div>
</div>
<div class="row">
	<div class="col-md-2">&nbsp;</div>
	<div class="col-md-8">

			<h1><small>Donation History</small></h1>
			<table class="table table-striped table-bordered table-hover">
  			<tr>
    				<th>DonorID</th>
    				<th>Donor Name</th>
    				<th>Donation Amount</th>
  			</tr>
			<% @donations.each do |donation| %>
  				<tr>
    					<td><%= donation.donorid %></td>
    					<td><%= donation.donorname %></td>
    					<td><%= donation.donationamount %></td>
  				</tr>
			<% end %>
			</table>
		
	</div>
	<div class="col-md-2">&nbsp;</div>
</div>

DonationWeb/app/views/donations/new.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">
        Donation Nation
      </a>
    </div>	
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/donations">Home <span class="sr-only">(current)</span></a></li>
        <li class="active"><a href="/donations/new">Make Donation</a></li>
      </ul>
  </div>
</nav>
<div class="row">
	<div class="col-md-2">&nbsp;</div>
	<div class="col-md-8">
		<%= form_for :donations, html: {role: "form", class:"form-horizontal"}, url: donations_path do |f| %>
  			<div class="form-group">
    				<%= f.label :id, class: "control-label col-sm-2" %>
				<div class="col-sm-10">
    					<%= f.text_field :donorid, class: "form-control" %>
				</div>
   			</div>
			<div class="form-group">
    				<%= f.label :name, class: "control-label col-sm-2" %>
				<div class="col-sm-10">
    					<%= f.text_field  :donorname, class: "form-control" %>
				</div>
			</div>
			<div class="form-group">
				<%= f.label :amount, class: "control-label col-sm-2" %>
				<div class="col-sm-10">
    					<%= f.text_field  :donationamount, class: "form-control" %>
				</div>
			</div>
    		<%= f.submit 'Donate Now!', :class => "btn btn-primary btn-lg" %>

		<% end %>

	</div>
	<div class="col-md-2">&nbsp;</div>
</div>

DonationWeb/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Donation Nation</title>
  <%= stylesheet_link_tag "bootstrap" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>